### ISSUE TITLE
[Feature Request] Keep recipe & Add config for setting the time it takes to craft an item

### ISSUE THREAD

**Issue by Qonsyuma** [Lolcroc/ProjectLepton#1]
My requests have been pretty much described in the title, being able to set a checkbox (or any other way to toggle something) that allows you to make the block keep the crafting recipe, even if it needs the materials from the recipe field to do so.

And then a config option (best would be ingame-changeable of course), for setting the time it takes to craft an item, so that you could even set it to be as fast as redstone allows.

**Comment by mont-40** [comment]
Great suggestions, working on an implementation atm
