### ISSUE TITLE
Crafting Automat only works in Single Player

### ISSUE THREAD

**Issue by Nahkranoth0** [Lolcroc/ProjectLepton#11]
**Forge version:** 34.1.42 1.16.3
**Mod version:** 1.2.2

**Mods list:**

1. [FORGE] Iron Furnaces (by XenoMustache)
2. Advanced Mining Dimension (by henkelmax)
3. AI Improvements (by DarkGuardsman)
4. AIOT Botania (by MelanX)
5. Apotheosis (by Shadows_of_Fire)
6. AppleSkin (by squeek502)
7. Aquaculture 2 (by Shadowclaimer)
8. AutoRegLib (by Vazkii)
9. Back Tools (by ohaiiChun)
10. Bad Wither No Cookie - Reloaded (by Kreezxil)
11. Basic Nether Ores [Forge/Fabric] (by cScotPlay)
12. Better Advancements (by way2muchnoise)
13. Better Muffling (by Korti11)
14. Biomes O' Plenty (by Forstride)
15. Bookshelf (by DarkhaxDev)
16. Botania (by Vazkii)
17. Botanical Machinery (by MelanX)
18. Botany Pots (by DarkhaxDev)
19. Botany Trees (by DarkhaxDev)
20. Builders Crafts & Additions (Forge) (by MRHminer)
21. Caelus API (Forge) (by TheIllusiveC4)
22. Campfire Torches (by enemeez1)
23. Classic Bars (by tfarecnim)
24. Click Machine (by Shadows_of_Fire)
25. Cloth Config API (Forge) (by shedaniel)
26. Clumps (by Jaredlll08)
27. Collective (by Serilum)
28. Comforts (by TheIllusiveC4)
29. Compressium (by DinnerBeef)
30. Construction Wand (by ThetaDev)
31. ContentTweaker (by Jaredlll08)
32. Controlling (by Jaredlll08)
33. Cooking for Blockheads (by BlayTheNinth)
34. Crafting Automat (by Loldoggy)
35. Crafting Station (by tfarecnim)
36. Crafting Tweaks (by BlayTheNinth)
37. CraftTweaker (by Jaredlll08)
38. Cucumber Library (by BlakeBr0)
39. Curio of Undying (Forge) (by TheIllusiveC4)
40. Curios API (Forge) (by TheIllusiveC4)
41. Curious Elytra (Forge) (by TheIllusiveC4)
42. Curious Jetpacks (by tfarecnim)
43. Curious Shulker Boxes (Forge) (by TheIllusiveC4)
44. Dark Utilities (by DarkhaxDev)
45. Enchant With Mob (by bagu_chan)
46. Enchantment Descriptions (by DarkhaxDev)
47. FallingTree (by RakSrinaNa)
48. FastFurnace (by Shadows_of_Fire)
49. FastWorkbench (by Shadows_of_Fire)
50. FTB Backups (by FTB)
51. FTB Essentials (by FTB)
52. FTB GUI Library (by FTB)
53. FTB Ranks (by FTB)
54. FTB Ultimine (by FTB)
55. Gateways to Eterrnity (by Shadows_of_Fire)
56. GraveStone Mod (by henkelmax)
57. Hwyla (by TehNut)
58. iChunUtil (by ohaiiChun)
59. Inventory Essentials (by BlayTheNinth)
60. Inventory Tweaks Renewed (by David1544)
61. Iron Chests (by ProgWML6)
62. Iron Jetpacks (by BlakeBr0)
63. Iron Shulker Boxes (by ProgWML6)
64. JEITweaker (by Jaredlll08)
65. Just Enough Items (JEI) (by mezz)
66. Just Enough Resources (JER) (by way2muchnoise)
67. LibX (by noeppinoeppi)
68. Light Overlay (Rift/Forge/Fabric) (by shedaniel)
69. Macaw's Bridges (by sketch_macaw)
70. Macaw's Roofs (by sketch_macaw)
71. Mana Gear (by Partonetrain)
72. Mantle (by mDiyo)
73. McJtyLib (by McJty)
74. Morpheus (by Quetzi)
75. Mouse Tweaks (by YaLTeR)
76. MrCrayfish's Furniture Mod (by MrCrayfish)
77. MythicBotany (by noeppinoeppi)
78. Neat (by Vazkii)
79. No Hostiles Around Campfire (by Serilum)
80. Open Loader (by DarkhaxDev)
81. OpenBlocks Elevator (by vsngarcia)
82. Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
83. Patchouli (by Vazkii)
84. Placebo (by Shadows_of_Fire)
85. Project MMO (by Harmonised_)
86. Quark (by Vazkii)
87. Quark Oddities (by Vazkii)
88. Reap Mod (by henkelmax)
89. ReAuth (by TechnicianLP)
90. Repurposed Structures (Forge) (by telepathicgrunt)
91. RFTools Base (by McJty)
92. RFTools Power (by McJty)
93. Runelic (by DarkhaxDev)
94. Silent Gear (by SilentChaos512)
95. Silent Lib (by SilentChaos512)
96. Silent's Gems (by SilentChaos512)
97. Simple Storage Network (by Lothrazar)
98. Sound Device Options (by ichttt)
99. Spiders 2.0 (by TheCyberBrick)
100. Storage Drawers (by Texelsaur)
101. SwingThroughGrass (by exidex)
102. The Weirding Gadget (by AtomicBlom)
103. Trample Stopper (by UnRealDinnerbone)
104. TrashSlot (by BlayTheNinth)
105. U Team Core (by HyCraftHD)
106. Useful Backpacks (by HyCraftHD)
107. VoxelMap (by MamiyaOtaru)
108. Waila Harvestability (by squeek502)
109. Wawla - What Are We Looking At (by DarkhaxDev)
110. YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
111. YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)

Hey there, i have installed your mod for the automation possibilities and tested this a lot on Single Player and worked like a charm but i've installed it now on my server and it doesn't work at all. the recipes are ok and valid according to the automat but regardless of the redstone signal (lever, redstone, button, etc) it doesn't do anything at all.

**Comment by Nahkranoth0** [comment]
Just tested on a fresh server, putting one mod at a time, and it worked.
In the version history of my modpack, i've removed these mods (resulting in them staying inactive in the world):
- Farmer's Delight
- FastLeafDecay
- QuickTP
- QuickHomes
- Essentials
- Global Resource & Data Pack

I'm much more inclined to either Farmer's Delight or Essentials

**Comment by mont-40** [comment]
I'm closing this issue for now. Future versions of CA will switch to another mechanism to check recipe ingredients, avoiding bugs such as the one you mentioned
