### ISSUE TITLE
Crafting rockets

### ISSUE THREAD

**Issue by manzipan** [Lolcroc/ProjectLepton#12]
very nice mod i use it on server with 1.16.5 only issue im getting is i cannot autocraft rockets which is the reason i downloaded this mod the recipie shows up on the crafting i can manualy craft it but no autocrafting is there a way to fix this

**Comment by mont-40** [comment]
No unfortunately you can't for rockets, books, maps, etc. So sorry you can't use this mod but it's planned for next versions

**Comment by mont-40** [comment]
Duplicate of #10. Closing this issue for now
