### ISSUE TITLE
Incompatible with Project MMO

### ISSUE THREAD

**Issue by MrGemaxos** [Lolcroc/ProjectLepton#13]
Im using 1.16.5 and i use the CurseForge Launcher.

I can't take out the crafted item from the inventory nor does the crafting table ever dispense the crafted item when activated with redstone. It seems like the crafted item just goes instantly back into the table after being clicked on, so I can't take it out.

Ive tested a few hours to get whats wrong and i think i pinned it down to an incompatibility with Project MMO
A clean install without it worked, even after putting back the other mods i use.
But if u have installed it once, the profile seem to be doomed for crafting automat.
A strange discovery was that it worked for a few second after installing PMMO and starting a "new world", but then (seemingly)after getting the recipies it breaks and then the profile is doomed :s

Is there a chance to check whats happening there? I would love to use these mods together, but i dont really know where to start working it out.

**Comment by RazzaSumma** [comment]
I'm having same issue as OP with Project MMO installed in the mods folder. I am on 1.18.1 version however.  I got the Auto-crafter to work again after setting useReqEnabled (in pmmo-common.toml in the config folder) to false. (Maybe setting it to false will work for OP for their 1.16.5 versions.) I also have craftReqEnabled set to false as well. (Will test if that affects the machine as well.)

**Comment by RazzaSumma** [comment]
For the 1.18.1 version with both pMMO and Crafting Automat installed, setting the field craftReqEnabled = false in the pmmo-common.toml in the config folder will enable the Automat machine to work. It works perfectly after that. 

Setting craftReqEnabled = false in 1.16.5 will work on new worlds but not on worlds that had the field set true previously.

**Comment by mont-40** [comment]
I'm closing this issue for now. Future versions of CA will switch to another mechanism to check crafting ingredients that won't produce bugs like these
