### ISSUE TITLE
Incompatibility with Mystical Agriculture infusion crystals

### ISSUE THREAD

**Issue by VulpiniLagopus** [Lolcroc/ProjectLepton#14]
If I put an infusion crystal (from mystical aggradations) with 500 charges in the crafting grid, and an infusion crystal with 753 charges in the ingredients part, after one successful use the infusion crystal with 753 charges goes down to 500 charges and the one with 500 charges to 499 and it won't be usable again. Also it works perfectly with master infusion crystal that has infinite charges. [https://youtu.be/TBm6GZI2sew](url)

**Comment by VulpiniLagopus** [comment]
Also if you use an infusion crystal in the crafting grid, and a master infusion crystal in the ingredients, it turns the master infusion crystal into a normal infusion crystal

**Comment by mont-40** [comment]
I'm closing this issue for now. Future versions of CA will change how recipe ingredients are handled, fixing bugs such as these
