### ISSUE TITLE
Items ejected/dispensed when destination full.

### ISSUE THREAD

**Issue by korg** [Lolcroc/ProjectLepton#23]
Im trying to built an autocrafting system on the cheap in the mod Colonial Create and i was using laserio to put in 1 stick and 1 coal to make 4 torches. I used a redstone clock to activate.

I placed a chest in front of the crafter and it started to fill the chest. I filled all the other slots in the chest and it filled the chest then started spitting out torches into the world.

I guess i expected it to stop crafting once the chest was full, or to have some way to stop it (other than not feeding it any more resources).

**Comment by mont-40** [comment]
Hi Korg, thanks for your feedback. This is actually intended behavior, like droppers and dispensers. The best (and easiest) way to mitigate overflow is to use a [comparator ](https://minecraft.fandom.com/wiki/Redstone_Comparator#Fullness_of_containers) on whatever inventory you're filling, and have its output fed back in the automat whenever the signal strength crosses a certain threshold.
