### ISSUE TITLE
Forge 1.20.1 version? 

### ISSUE THREAD

**Issue by Daotaku** [Lolcroc/ProjectLepton#28]
Hey, any thought on updating to the 1.20.1 version minecraft? 

I've used your mods on 1.19 and loved it, but I'm now playing on 1.20.1 and it's not working anymore.

Thanks.

**Comment by phampyk** [comment]
Waiting for this too! This mod is the reason out little server hasn't updated to 1.20.1 yet! We use it a lot

**Comment by mont-40** [comment]
Updated! Happy crafting :)
