### ISSUE TITLE
[Feature Request] Slot locking

### ISSUE THREAD

**Issue by REBeq** [Lolcroc/ProjectLepton#32]
Can you add slot locking to reserve slots to specific items? Crafting clogs a lot when i pipe items into in and stops working.

**Comment by mont-40** [comment]
Thanks for your suggestion! However I don't have plans to add this feature for two reasons:
1. The new Crafter in Minecraft 1.21 has this functionality (as long as you keep the recipe inside). I don't have any concrete plans to merge or override the features of the Crafter, so until that time and while I keep the mod updated you can use both types of autocrafters side by side.
2. The problem you describe is logistical in nature. Although slot locking is an easy solution, I want to keep this mod bare-bones and vanilla-friendly on purpose to add some challenge. Vanilla and other mods have functionality that let you control item flows with some clever designs.
