### ISSUE TITLE
Disable/enable on redstone power instead of pulse

### ISSUE THREAD

**Issue by mont-40** [Lolcroc/ProjectLepton#7]
Add an option to enable/disable the automat by a constant redstone signal, instead of a single pulse. In this mode something like a lever in the 'on' position or redstone block will keep the automat active and it will craft as soon as it can

**Comment by mont-40** [comment]
Feature push with new build, example at https://i.imgur.com/apDflkR.mp4

**Comment by MrDomino4195** [comment]
where is this feature in the 1.20.1 version?
